language: c
sudo: required

matrix:
  include:
    # open_memstream
    - compiler: gcc
    # fopencookie
    - env: [CMAKE_EXTRA_ARGS=-DHAVE_OPEN_MEMSTREAM=FALSE]
      compiler: gcc
    # tmpfile
    - env: [CMAKE_EXTRA_ARGS=-DHAVE_OPEN_MEMSTREAM=FALSE -DHAVE_FOPENCOOKIE=FALSE]
      compiler: gcc
    # funopen
    - os: osx

before_install:
- sudo apk-add-repository -y ppa:snaipewastaken/soft
- sudo apt-get update
- sudo apt-get install -qq -y criterion-dev

script:
- mkdir build && cd $_
- cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ${CMAKE_EXTRA_ARGS} ..
- make
- ./test/unit_tests
