language: c
compiler: gcc
sudo: required

matrix:
  include:
    # open_memstream
    - env: []
    # fopencookie
    - env: [CMAKE_EXTRA_ARGS=-DHAVE_OPEN_MEMSTREAM=FALSE]
    # tmpfile
    - env: [CMAKE_EXTRA_ARGS=-DHAVE_OPEN_MEMSTREAM=FALSE -DHAVE_FOPENCOOKIE=FALSE]
    # funopen
    - env: []
      os: osx

before_install:
- sudo apk-add-repository -y ppa:snaipewastaken/soft
- sudo apt-get update
- sudo apt-get install -qq -y criterion-dev

script:
- mkdir build && cd $_
- cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ${CMAKE_EXTRA_ARGS} ..
- make
- ./test/unit_tests
