language: c
sudo: required

matrix:
  include:
    # open_memstream
    - compiler: gcc
    # fopencookie
    - env: [CMAKE_EXTRA_ARGS="-DHAVE_OPEN_MEMSTREAM=FALSE"]
      compiler: gcc
    # tmpfile
    - env: [CMAKE_EXTRA_ARGS="-DHAVE_OPEN_MEMSTREAM=FALSE -DHAVE_FOPENCOOKIE=FALSE"]
      compiler: gcc
    # funopen
    - os: osx

before_install:
- |
    if [ "${TRAVIS_OS_NAME}" = linux ]; then
      sudo add-apt-repository -y ppa:snaipewastaken/ppa
      sudo apt-get update
      sudo apt-get install -qq -y criterion-dev
    else
      brew install snaipe/soft/criterion
    fi

script:
- mkdir build && cd $_
- cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ${CMAKE_EXTRA_ARGS} ..
- make
- ./test/unit_tests
